name: CD - Deploy functions

on:
  push:
    branches: ["release/**"]
    paths:
        - ".github/workflows/deploy-functions.yml"
        - "functions/emailSenderFnc/**"

jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - uses: dorny/paths-filter@v3
        id: path-filter
        with:
          base: ${{ github.ref }}
          filters: |
            workflow:
              - ".github/workflows/deploy-functions.yml"
            emailSenderFnc:
              - "functions/emailSenderFnc/**"

      - name: Google auth
        uses: google-github-actions/auth@v2
        id: gcp-auth
        with:
          credentials_json: '${{ secrets.GOOGLE_APP_CREDENTIALS_BASE64 }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        id: set-gcloud
        with:
           project_id: '${{ secrets.GOOGLE_PROJECT_ID }}'

      - name: Deploy cloud create key function
        id: deploy-email-sender-func
        if: |
          steps.path-filter.outputs.emailSenderFnc == 'true' || 
          steps.path-filter.outputs.workflow == 'true'
        run: |
          gcloud functions deploy EmailSenderFnc \
            --project ${{ secrets.GOOGLE_PROJECT_ID }} \
            --no-allow-unauthenticated \
            --region=${{ secrets.REGION }} \
            --trigger-http \
            --runtime=${{ secrets.RUNTIME }} \
            --update-labels=module=signatures \
            --source=.

  dockerhub:
    runs-on: ubuntu-latest
    needs: [gcp]
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - uses: dorny/paths-filter@v3
        id: path-filter
        with:
          base: ${{ github.ref }}
          filters: |
            workflow:
              - ".github/workflows/deploy-functions.yml"
            emailSenderFnc:
              - "functions/emailSenderFnc/**"

      - name: Docker hub login
        id: docker-hub-login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - uses: docker/build-push-action@v5
        name: Build and push image
        id: build-and-push
        if: |
          steps.path-filter.outputs.emailSenderFnc == 'true' || 
          steps.path-filter.outputs.workflow == 'true'
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_IMAGE_TAG}}

