name: CD - Deploy functions

on:
  push:
    branches: ["trunk/**"]
    paths:
        - ".github/workflows/deploy-functions.yml"
        - "functions/emailSenderFnc/**"

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    needs: [gcp]
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - uses: dorny/paths-filter@v3
        id: path-filter
        with:
          base: ${{ github.ref }}
          filters: |
            workflow:
              - ".github/workflows/deploy-functions.yml"
            emailSenderFnc:
              - "functions/emailSenderFnc/**"

      - name: Docker hub login
        id: docker-hub-login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - uses: docker/build-push-action@v5
        name: Build and push image
        id: build-and-push
        if: |
          steps.path-filter.outputs.emailSenderFnc == 'true' || 
          steps.path-filter.outputs.workflow == 'true'
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_IMAGE_TAG}}-alpha

