name: CI - Tests & Eslint 

on:
  push:
    paths:
        - ".github/workflows/**"
        - "functions/**"
    branches:
      - "feature/**"
      - "perf/**"
      - "refactor/**"
      - "bugfix/**"
      - "ci/**"
      - "chore/**"
      - "release/**"
      - "hotfix/**"
      - "support/**"
      - "dependabot/**"

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        node: [ 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v3
        id: git-clone
        name: Cloning repository

      - uses: pnpm/action-setup@v2
        id: install-pnpm
        name: Installing PNPM
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        id: set-nodejs
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        id: set-deps
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        id: unit-tests
        run: pnpm run test

  eslint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - uses: pnpm/action-setup@v3
        id: install-pnpm
        name: Installing PNPM
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        id: set-nodejs
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install dependencies
        id: set-deps
        run: pnpm install --frozen-lockfile

      - name: Run Eslint
        id: eslint
        run: pnpm run lint
